services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333" # REST API и Web UI
      - "6334:6334" # GRPC API
    volumes:
      - ./qdrant_storage:/qdrant/storage # Хранение данных на хосте
    restart: unless-stopped
